// <auto-generated/>
using System.Runtime.CompilerServices;

namespace Cake.ReSharperReports
{
    /// <summary>
    /// This namespace contains Gitter aliases.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}


namespace Cake.ReSharperReports.Provider
{
    /// <summary>
    /// This namespace contains Gitter aliases.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}