// <auto-generated/>
using System.Runtime.CompilerServices;

namespace Cake.ReSharperReports
{
    /// <summary>
    /// This namespace contains ReSharperReports aliases.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}


namespace Cake.ReSharperReports.Provider
{
    /// <summary>
    /// This namespace contains types used by ReSharperReports tool.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

namespace Cake.ReSharperReports.Transform
{
    /// <summary>
    /// This namespace contains types for ReSharperReports tool.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}