//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System;

[assembly: AssemblyTitle("Cake.ReSharperReports")]
[assembly: AssemblyDescription("Cake ReSharperReports AddIn")]
[assembly: AssemblyCompany("gep13")]
[assembly: AssemblyProduct("Cake.ReSharperReports")]
[assembly: AssemblyVersion("0.3.1")]
[assembly: AssemblyFileVersion("0.3.1")]
[assembly: AssemblyInformationalVersion("0.3.1")]
[assembly: AssemblyCopyright("Copyright © gep13 2016 - Present")]
[assembly: CLSCompliant(true)]

